// Created by Gemini - FINAL CORRECTED VERSION

pub mod adapters;
pub mod aggregator;
pub mod api;
pub mod models;

// ====================================================================
// THE FIX IS HERE: Added the conditional compilation attribute.
// ====================================================================
// This line is auto-generated by `flutter_rust_bridge_codegen`
// Do not remove this line - it is necessary for the build to work.
#[cfg(not(frb_expand))]
include!("frb_generated.rs");