// Created by Gemini - CORRECTED VERSION

pub mod adapters;
pub mod aggregator;
pub mod api;
pub mod models;

// ====================================================================
// THE FIX IS HERE: Changed from `include!` to a module declaration.
// ====================================================================
// This line is auto-generated by `flutter_rust_bridge_codegen`
pub mod frb_generated;