// Created by Gemini - CORRECTED VERSION
// This file makes the `models` module available to the rest of the crate.
// It includes the Rust code that was auto-generated by `prost-build`
// from your .proto files during the build process.

// The `include!` macro pastes the contents of the generated file here at compile time.
// The file path is determined by the `OUT_DIR` environment variable, which Cargo sets.
include!(concat!(env!("OUT_DIR"), "/models.rs"));